example_name: gpt
model_name: gpt2
# convert_to_ft:
#   script: hf_gpt_convert.py
#   output_dir: ./c-model/gpt2/1-gpu
#   args:
#     # Must be the path to the downloaded model
#     # Model will always be downloaded to
#     # /src/models/<model_name>/
#     in-file: /src/models/gpt2/
#     out-dir: ./c-model/gpt2
#     tensor-parallelism: 1
#     storage-type: float16
build:
  script: build.py
  output_dir: ./engine_outputs/gpt2/1-gpu
  args:
    model_dir: ./c-model/gpt2/1-gpu
    output_dir: ./engine_outputs/gpt2/1-gpu
    # Keys without values are treated as flags
    use_gpt_attention_plugin: 
    remove_input_padding: 


