model_id: gpt2-medium
example_name: gpt
convert_to_ft:
  script: hf_gpt_convert.py
  output_dir: ./c-model/gpt2/1-gpu
  args:
    in-file: /src/models/gpt2-medium
    out-dir: ./c-model/gpt2
    tensor-parallelism: 1
    storage-type: float16
build:
  script: build.py
  output_dir: ./engine_outputs/
  args:
    model_dir: ./c-model/gpt2/1-gpu
    output_dir: ./engine_outputs/
    dtype: float16
    use_gpt_attention_plugin: float16
    hidden_act: gelu
    use_inflight_batching: null
    paged_kv_cache: null
    use_gemm_plugin: float16
    remove_input_padding: null
    use_layernorm_plugin: float16
    parallel_build: null
merge: true
